// Build-time generator for lib/land.ts
//
// Fetches a low-resolution Natural Earth 110m land GeoJSON (cached into
// data/ne_110m_land.geojson on first run), rasterizes it into a ~2.5 degree
// grid of [lat, lon] land points via point-in-polygon, and bakes the result
// into lib/land.ts so the globe never makes a runtime network call.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA_DIR = path.join(ROOT, "data");
const GEO_PATH = path.join(DATA_DIR, "ne_110m_land.geojson");
const OUT_PATH = path.join(ROOT, "lib", "land.ts");

const GRID_DEG = 2.5;

const SOURCES = [
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson",
  "https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json",
];

async function loadGeo() {
  // Prefer a cached copy so builds are reproducible and offline-safe.
  try {
    const cached = await fs.readFile(GEO_PATH, "utf8");
    console.log(`[gen-land] using cached ${path.relative(ROOT, GEO_PATH)}`);
    return JSON.parse(cached);
  } catch {
    /* fall through to fetch */
  }

  for (const url of SOURCES) {
    try {
      console.log(`[gen-land] fetching ${url}`);
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const text = await res.text();
      const json = JSON.parse(text);
      await fs.mkdir(DATA_DIR, { recursive: true });
      await fs.writeFile(GEO_PATH, text);
      console.log(`[gen-land] cached -> ${path.relative(ROOT, GEO_PATH)}`);
      return json;
    } catch (err) {
      console.warn(`[gen-land] source failed: ${err.message}`);
    }
  }
  throw new Error(
    "[gen-land] could not obtain Natural Earth land GeoJSON (no cache, all sources failed)"
  );
}

/** Ray-casting point-in-ring test on the lon/lat plane. ring: [[lon,lat],...] */
function pointInRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0];
    const yi = ring[i][1];
    const xj = ring[j][0];
    const yj = ring[j][1];
    const intersect =
      yi > lat !== yj > lat &&
      lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

/** polygon: [outerRing, hole1, hole2, ...] */
function pointInPolygon(lon, lat, polygon) {
  if (!polygon.length) return false;
  if (!pointInRing(lon, lat, polygon[0])) return false;
  for (let h = 1; h < polygon.length; h++) {
    if (pointInRing(lon, lat, polygon[h])) return false; // inside a hole
  }
  return true;
}

function collectPolygons(geo) {
  const polys = [];
  const features = geo.type === "FeatureCollection" ? geo.features : [geo];
  for (const f of features) {
    const g = f.geometry || f;
    if (!g) continue;
    if (g.type === "Polygon") {
      polys.push(g.coordinates);
    } else if (g.type === "MultiPolygon") {
      for (const p of g.coordinates) polys.push(p);
    }
  }
  return polys;
}

/** Bounding boxes for fast rejection. */
function bbox(polygon) {
  let minX = Infinity,
    minY = Infinity,
    maxX = -Infinity,
    maxY = -Infinity;
  for (const [x, y] of polygon[0]) {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return { minX, minY, maxX, maxY };
}

async function main() {
  const geo = await loadGeo();
  const polygons = collectPolygons(geo);
  const boxes = polygons.map(bbox);

  const points = [];
  for (let lat = -90 + GRID_DEG / 2; lat < 90; lat += GRID_DEG) {
    for (let lon = -180; lon < 180; lon += GRID_DEG) {
      let isLand = false;
      for (let k = 0; k < polygons.length; k++) {
        const b = boxes[k];
        if (lon < b.minX || lon > b.maxX || lat < b.minY || lat > b.maxY)
          continue;
        if (pointInPolygon(lon, lat, polygons[k])) {
          isLand = true;
          break;
        }
      }
      if (isLand) {
        points.push([
          Math.round(lat * 100) / 100,
          Math.round(lon * 100) / 100,
        ]);
      }
    }
  }

  const body =
    "// AUTO-GENERATED by scripts/gen-land.mjs — do not edit by hand.\n" +
    "// Natural Earth 110m land rasterized to a ~2.5 degree [lat, lon] grid.\n" +
    `// ${points.length} land points. Regenerate with: npm run gen:land\n\n` +
    "export const LAND: [number, number][] = [\n" +
    points.map(([la, lo]) => `  [${la}, ${lo}],`).join("\n") +
    "\n];\n";

  await fs.mkdir(path.join(ROOT, "lib"), { recursive: true });
  await fs.writeFile(OUT_PATH, body);
  console.log(
    `[gen-land] wrote ${path.relative(ROOT, OUT_PATH)} with ${points.length} points`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
